name: arXiv-daily

on:
  push:
    branches: [ "main" ]          # 提交到 main 就会触发一次（用于“唤醒”）
  schedule:
    - cron: "30 16 * * *"         # 每天 16:30 UTC
  workflow_dispatch:               # 允许手动跑

permissions:
  contents: write                  # 允许用 GITHUB_TOKEN 回写仓库

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (uv)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: Print config (debug)
        run: |
          echo "CATEGORIES=${{ vars.CATEGORIES }}"
          echo "LANGUAGE=${{ vars.LANGUAGE }}"
          echo "MODEL_NAME=${{ vars.MODEL_NAME }}"

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          LANGUAGE: ${{ vars.LANGUAGE }}
          CATEGORIES: ${{ vars.CATEGORIES }}
          MODEL_NAME: ${{ vars.MODEL_NAME }}
        run: |
          source .venv/bin/activate
          bash run.sh

      - name: Commit & Push
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name  "${{ vars.NAME }}"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "update"
          git config pull.rebase true
          git config rebase.autoStash true
          for i in 1 2 3; do
            if git push origin main; then
              echo "Push successful"; break
            else
              echo "Push failed, pulling latest changes..."
              git pull origin main --no-edit || true
              [ "$i" = "3" ] && exit 1
            fi
          done
